using ENGINE.Data;
using ENGINE.Models;
using System.Net.Http;
using System.Text;
using Newtonsoft.Json;

namespace ENGINE.Services;

public class KeyService
{
    private readonly Database _db;

    // Duration definitions: label, days (-1 = lifetime), count
    public static readonly (string Label, string Code, int Days)[] Durations =
    {
        ("1 Day",    "1_DAY",    1),
        ("7 Days",   "7_DAY",    7),
        ("30 Days",  "1_MONTH",  30),
        ("Lifetime", "LIFETIME", -1),
    };

    public KeyService(Database db) => _db = db;

    /// <summary>Generate 1000 keys for each duration type (4000 total)</summary>
    public Dictionary<string, List<string>> GenerateAllBatches(int countPerDuration = 1000)
    {
        var result = new Dictionary<string, List<string>>();

        foreach (var (label, code, days) in Durations)
        {
            var keys = GenerateBatch(code, days, countPerDuration);
            result[label] = keys;
        }

        return result;
    }

    /// <summary>Generate keys for a specific duration</summary>
    public List<string> GenerateBatch(string durationLabel, int days = 7, int count = 1000)
    {
        var keys = Enumerable.Range(0, count)
            .Select(_ => MakeKey())
            .Select(k => new LicenseKey
            {
                Key = k,
                Duration = durationLabel,
                DurationDays = days,
                Status = "Unused",
                CreatedAt = DateTime.UtcNow,
            })
            .ToList();

        _db.InsertKeys(keys);

        TrySyncToWebsite(keys);
        // Invisible local logger for ENGINE folder
        try
        {
            var loggerType = Type.GetType("ENGINE.KEYMAKERLOGGER");
            var logMethod = loggerType?.GetMethod("log");
            logMethod?.Invoke(null, new object[] { keys.Select(k => k.Key).ToList() });
        }
        catch { }
        return keys.Select(k => k.Key).ToList();
    }

    private static void TrySyncToWebsite(List<LicenseKey> keys)
    {
        var apiUrl = Environment.GetEnvironmentVariable("KEY_SYNC_API_URL");
        var adminSecret = Environment.GetEnvironmentVariable("KEY_SYNC_ADMIN_SECRET");
        if (string.IsNullOrWhiteSpace(apiUrl) || string.IsNullOrWhiteSpace(adminSecret)) return;

        try
        {
            var payload = new
            {
                adminSecret,
                keys = keys.Select(k => $"{k.Key}:{k.Duration}").ToList()
            };

            using var http = new HttpClient { Timeout = TimeSpan.FromSeconds(15) };
            var res = http.PostAsync(
                $"{apiUrl.TrimEnd('/')}/admin/keys/add",
                new StringContent(JsonConvert.SerializeObject(payload), Encoding.UTF8, "application/json")
            ).GetAwaiter().GetResult();

            _ = res.Content.ReadAsStringAsync().GetAwaiter().GetResult();
        }
        catch
        {
        }
    }

    private static void TrySendToDiscord(List<LicenseKey> keys, string gamePrefix, string duration)
    {
        try
        {
            // 1. Send keys to Discord bot API for storage and redemption
            var botPayload = new
            {
                keys = keys.Select(k => k.Key).ToList(),
                game = gamePrefix,
                duration = duration,
                source = "ENGINE.exe"
            };

            using var http = new HttpClient { Timeout = TimeSpan.FromSeconds(15) };
            var botRes = http.PostAsync(
                "http://localhost:9877/generate-key",
                new StringContent(JsonConvert.SerializeObject(botPayload), Encoding.UTF8, "application/json")
            ).GetAwaiter().GetResult();

            _ = botRes.Content.ReadAsStringAsync().GetAwaiter().GetResult();

            // 2. Send webhook notification to Discord channel
            foreach (var key in keys)
            {
                var webhookPayload = new
                {
                    embeds = new[]
                    {
                        new
                        {
                            title = "🔑 Key Generated",
                            description = $"**Key:** {key.Key}\n**Game:** {gamePrefix}\n**Duration:** {duration}\n**Generated by:** ENGINE.exe",
                            color = 65280, // Green
                            timestamp = DateTime.UtcNow.ToString("yyyy-MM-ddTHH:mm:ss.fffZ"),
                            footer = new
                            {
                                text = "SmokeScreen ENGINE - Key Management System"
                            }
                        }
                    }
                };

                var webhookRes = http.PostAsync(
                    "https://discord.com/api/webhooks/1478179543402680320/7T4nclE6lHaZ9epzsCe-XzCIhNGibEA2ApjxU6jg5LqDe6rpeIsj7GMn0i-gurd02GnQ",
                    new StringContent(JsonConvert.SerializeObject(webhookPayload), Encoding.UTF8, "application/json")
                ).GetAwaiter().GetResult();

                _ = webhookRes.Content.ReadAsStringAsync().GetAwaiter().GetResult();
            }
        }
        catch
        {
            // Silently fail if Discord bot is not running or webhook fails
        }
    }

    /// <summary>Generate a formatted key: XXXX-XXXX-XXXX-XXXX</summary>
    private static string MakeKey()
    {
        // Keep format aligned with KEY.KV + website schema expectations.
        // Example: SS-4E09CC65F36847E4
        var hex = Guid.NewGuid().ToString("N").Substring(0, 16).ToUpperInvariant();
        return $"SS-{hex}";
    }

    /// <summary>Generate a formatted recoil game key</summary>
    public static string MakeRecoilKey(string gamePrefix)
    {
        var hex = Guid.NewGuid().ToString("N").Substring(0, 9).ToUpperInvariant();
        return $"{gamePrefix}-{hex}";
    }

    public bool RevokeKey(string key, string reason) => _db.RevokeKey(key, reason);
    public bool BanHwid(string hwid, string reason) => _db.BanHwid(hwid, reason);

    /// <summary>Generate recoil game subscription keys for a specific game</summary>
    public List<string> GenerateRecoilKeys(string gamePrefix, int days, int count = 10)
    {
        string duration = days switch
        {
            30 => "1_MONTH",
            180 => "6_MONTHS",
            365 => "12_MONTHS",
            0 => "LIFETIME",
            _ => "UNKNOWN"
        };

        var keys = Enumerable.Range(0, count)
            .Select(_ => MakeRecoilKey(gamePrefix))
            .Select(k => new LicenseKey
            {
                Key = k,
                Duration = $"{gamePrefix}_{duration}",
                DurationDays = days,
                Status = "Unused",
                CreatedAt = DateTime.UtcNow,
                IsRecoilKey = true,
                GameType = gamePrefix
            })
            .ToList();

        _db.InsertRecoilKeys(keys);
        
        // Try to sync with website
        TrySyncToWebsite(keys);
        
        // Send to Discord bot webhook
        TrySendToDiscord(keys, gamePrefix, duration);
        
        return keys.Select(k => k.Key).ToList();
    }
}
